addons:
  postgresql: 10
language: ruby
before_script:
  cp config/database.example.yml config/database.yml
rvm:
  - 2.5.1
script:
  - bin/rake db:create RAILS_ENV=test
  - bin/rake db:migrate RAILS_ENV=test
  - bin/rake
