addons:
  postgresql: 10
language: ruby
before_script:
  - cp config/database.example.yml config/database.yml
  - psql -c 'create database mission_us_test;' -U postgres
rvm:
  - 2.5.1
script:
  - bin/rake db:migrate RAILS_ENV=test
  - bin/rake
