addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433
language: ruby
before_script:
  - cp config/database.example.yml config/database.yml
  - psql -c 'create database mission_us_test;' -U postgres -W postgres
rvm:
  - 2.5.1
services:
  - postgresql
script:
  - bin/rake db:migrate RAILS_ENV=test
  - bin/rake
