addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433
before_script:
  - cp config/database.example.yml config/database.yml
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo service postgresql restart
  - sudo psql -c "create database mission_us_test;" -U postgres
services:
  - postgresql
job:
  include:
    - stage: test
      language: ruby
      rvm:
        - 2.5.1
      script:
        - bin/rake db:migrate RAILS_ENV=test
        - bundle exec rake spec
    - stage: jest
      language: node_js
      node_js: 10.8
      cache:
        yarn: true
      script:
        - yarn test

