default: &default
  adapter: postgresql
  encoding: unicode
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRESQL_USERNAME'] || 'postgres' %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] || 'postgres' %>
  host: localhost

development:
  <<: *default
  database: mission_us_development
  port: 5432

test:
  <<: *default
  encoding: utf8
  host: localhost
  timeout: 5000
  database: mission_us_test


staging:
  <<: *default
  database: mission_us_staging
  username: mission_us
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>

production:
  <<: *default
  database: mission_us_production
  username: mission_us
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
